# Directs the Travis CI build service for WorldWind Android
# For more information see https://docs.travis-ci.com/user/customizing-the-build/

# Set up to run the Android build script per the Travis CI documentation
language: android

# Configure the build to use Oracle JDK 8, required by Android API 24
jdk:
  - oraclejdk8

# Configure the Android build configuration to match the Gradle build
android:
  components:
    - platform-tools      # latest SDK platform-tools
    - tools               # latest SDK tools
    - android-23          # SDK version used to compile the project
    - build-tools-28.0.3  # minimum build tools compatible with Android Gradle plugin 3.3.x
    - extra-android-support
    - extra-android-m2repository

# Decrypt the keystore used to certify Android apps when the build is not a pull request
#before_script:
#  - 'if [[ -n "${encrypted_2eaf8cabe659_key}" ]]; then openssl aes-256-cbc -K "${encrypted_2eaf8cabe659_key}" -iv "${encrypted_2eaf8cabe659_iv}" -in keystore.jks.enc -out keystore.jks -d; fi'

# Build the project
script:
  - ./gradlew build --stacktrace

# Deployment has been disabled in preparation for the WorldWind project suspension on April 5, 2019
#deploy:
#  # Publish SNAPSHOT artifacts to oss.jfrog.org
#  - provider: script
#    script: ./gradlew worldwind:artifactoryPublish --stacktrace
#    skip_cleanup: true
#    on:
#      branch: develop
#  # Publish API documentation to GitHub Pages
#  - provider: pages
#    github_token: $GITHUB_API_KEY
#    local_dir: worldwind/build/outputs/doc/javadoc
#    skip_cleanup: true
#    on:
#      branch: develop
#  # Publish release artifacts to Bintray/JCenter
#  - provider: script
#    script: ./gradlew worldwind:bintrayUpload --stacktrace
#    skip_cleanup: true
#    on:
#      tags: true
#  # Create CHANGELOG.md in the current directory
#  - provider: script
#    script: ./travis/changelog.sh >> CHANGELOG.md
#    skip_cleanup: true
#    on:
#      tags: true
#  # Create a GitHub release and publish CHANGELOG.md to the release assets
#  - provider: releases
#    api_key: $GITHUB_API_KEY
#    file: CHANGELOG.md
#    skip_cleanup: true
#    on:
#      tags: true

# Android build cache configuration. See the Travis documentation: https://docs.travis-ci.com/user/languages/android#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
