# Directs the Travis CI build service for World Wind Android
# For more information see https://docs.travis-ci.com/user/customizing-the-build/

# Required to install the jq JSON filter used to parse GitHub API results
sudo: required

# Set up to run the Android build script per the Travis CI documentation
language: android

# Configure the build to use Oracle JDK 8, required by Android API 24
jdk:
  - oraclejdk8

# Configure the Android build configuration to match the Gradle build
android:
  components:
    - platform-tools      # latest SDK platform-tools
    - tools               # latest SDK tools
    - android-24          # SDK version used to compile the project
    - build-tools-25.0.3  # build tools used by the project
    - extra-android-support
    - extra-android-m2repository

# Decrypt the keystore used to certify Android apps when the build is not a pull request
before_script:
  - 'if [[ -n "${encrypted_2eaf8cabe659_key}" ]]; then openssl aes-256-cbc -K "${encrypted_2eaf8cabe659_key}" -iv "${encrypted_2eaf8cabe659_iv}" -in keystore.jks.enc -out keystore.jks -d; fi'

# Build the project
script:
  - ./gradlew build --stacktrace

# Deploy build artifacts. Travis does not invoke this step for pull request builds
deploy:
  # Publish release artifacts to Bintray/JCenter
  - provider: script
    script: ./gradlew worldwind:bintrayUpload --stacktrace
    skip_cleanup: true
    on:
      tags: true
  # Create CHANGELOG.md in the current directory
  - provider: script
    script: ./travis/changelog.sh >> CHANGELOG.md
    skip_cleanup: true
    on:
      tags: true
  # Create a GitHub release and publish CHANGELOG.md to the release assets
  - provider: releases
    api_key: $GITHUB_API_KEY
    file: CHANGELOG.md
    skip_cleanup: true
    on:
      tags: true

# Android build cache configuration. See the Travis documentation: https://docs.travis-ci.com/user/languages/android#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

# Notify the World Wind mailing list on every build
notifications:
  email:
    recipients:
      secure: DkCy9CqMXyRmRNYOt3pgN6kK/p5n4sVrW4qi2W6HDkolrBVSXYcLid1D9krMgcK7DhcWCbAusUdDh7vVjnnD9OaNanElN8sp0bOEtL0QJrPfcyVJdALO6qoZW+PCLLW7bgEjtbXBAY/u5sHTop/X2XWV1vM3Jx23eqvS5/UzbwyAqRvHjGreJG4RDMQhxOuk/yiXT1QB2sKcbZBn3nTaBQOjHsYENfAAxwh/Gr1XrS5RPg3UWV9N8vVW98nyIYYTQmtvu84M048wdub/fDH91XUQucpJtMKWjc9C/TwOhHEuk3hvg+w7GvqROPbVa1GVkw6b3bL1MVumAzd9SRESZmKxWI/EhqnlYFhkE88p1xjX5JX5sU7R5q+lGnh3pVL7E8nGBjthEdcvyqRGYxqACSY85Zdh70QjQ74Z4jLuwueLhiNaFVxE5cwEsVdW4ciZgCEbOHcUY3HuXRe7zYzKdAJN3+cUhwF9zZ0ABsxTowzgBZwzE6+kpmoQaV/VeWwJIe3+szedgk4cb+Hv4F1iILBMQ7avAeCdwcUzcP3B4SIG0wAT63JRJbERqTumchVmSycFP77sDgZ1wG5pi/DMxoSeCRqLBWnJAPLDnz/JEMhZl3+nEqtGUG69pymv5bsoCBPXCLeDZj5hNliZcP+Sm4RJgjNz0IILaSlEzJ+duto=
    on_success: always
    on_failure: always